<?php $title = 'Mon blog'; ?>

<?php ob_start(); ?>
<h1>REQUETE SQL </h1>
<?php require('menuJoker.phtml'); ?>

<div class="dd">
    <p>Liste de tous les sites</p>
     <pre>

         SELECT id, name, description,logo,proprietaire   FROM site
     </pre>
</div>


<div class="dd">
    <pre>
            <?php
                foreach ($sites as $site){
                    echo '<pre/>'.$site['id'].' '. $site['name'].' | '. $site['proprietaire'];echo '<br/>';
                }
            ?>

    </pre>
</div>



<?php
//$users->closeCursor();
?>
<?php $content = ob_get_clean(); ?>

<?php require('view/frontend/template.php'); ?>