                            <!--pour la presentation -->
<ul>
    <li><a class="color-joker__link" href="http://localhost:9000/admin">liste de tous les sites</a></li>
    <li><a class="color-joker__link" href="http://localhost:9000/admin/joker/style">liste de tous les style</a></li>
    <li><a class="color-joker__link" href="http://localhost:9000/admin/joker/styleBySite">Recupere tout les style d'un site => Many To Many</a></li>
    <li><a class="color-joker__link" href="http://localhost:9000/admin/joker/messageUser">Recupere tout les messages de l'utilisateur ayant pour id 1 => Many To One</a></li>
    <li><a class="color-joker__link" href="http://localhost:9000/admin/joker/postUser">Recupere tout les posts de utilisateur ayant pour id 1 => Many To One</a></li>
</ul>